@startuml
hide circle
hide empty members
skinparam linetype ortho
class "Menu" #00FF00
"Menu" --> "North American Open" : "Menu -> North American Open"
"Menu" --> "Katushai Challenge" : "Menu -> Katushai Challenge"
"Menu" --> "WAR Invitational" : "Menu -> WAR Invitational"
"Menu" --> "World Championship" : "Menu -> World Championship"
"Menu" --> "Jaguar Mechlab" : "Menu -> Jaguar Mechlab"
"Menu" --> "Shadow Mechlab" : "Menu -> Shadow Mechlab"
"Menu" --> "Thorn Mechlab" : "Menu -> Thorn Mechlab"
"Menu" --> "Pyros Mechlab" : "Menu -> Pyros Mechlab"
"Menu" --> "Electra Mechlab" : "Menu -> Electra Mechlab"
"Menu" --> "Katana Mechlab" : "Menu -> Katana Mechlab"
"Menu" --> "Shredder Mechlab" : "Menu -> Shredder Mechlab"
"Menu" --> "Flail Mechlab" : "Menu -> Flail Mechlab"
"Menu" --> "Gargoyle Mechlab" : "Menu -> Gargoyle Mechlab"
"Menu" --> "Chronos Mechlab" : "Menu -> Chronos Mechlab"
"Menu" --> "Nova Mechlab" : "Menu -> Nova Mechlab"
"Menu" --> "Pilot Training" : "Menu -> Pilot Training"
class "North American Open" #00FF00
"North American Open" : {method} North American Open - Beat Raven: Progressive Gargoyle ARM Speed
"North American Open" : {method} North American Open - Beat Crystal: Progressive Shadow ARM Power
"North American Open" : {method} North American Open - Beat Ibrahim: Progressive Endurance
"North American Open" : {method} North American Open - Beat Jack: Progressive Chronos LEG Power
"North American Open" : {method} North American Open - Beat Dr Lynn Yarr: Progressive Chronos LEG Speed
"North American Open" : {method} North American Open - Beat Shirro: Progressive Endurance
"North American Open" : {method} North American Open - Beat Milano: Progressive Flail Armor
"North American Open" : {method} North American Open - Beat Jean Paul: Progressive Jaguar Enhancement
"North American Open" : {method} North American Open - Beat Steffan: Progressive Flail LEG Speed
"North American Open" : {method} North American Open - Beat Cossette: Progressive Jaguar ARM Speed
"North American Open" : {method} Win North American Open: Progressive Gargoyle Stun Resist
class "Katushai Challenge" #00FF00
"Katushai Challenge" : {method} Katushai Challenge - Beat Jaqouline: Progressive Chronos LEG Speed
"Katushai Challenge" : {method} Katushai Challenge - Beat Prince Vassar: Progressive Electra LEG Speed
"Katushai Challenge" : {method} Katushai Challenge - Beat Steel Claw: Progressive Shadow ARM Speed
"Katushai Challenge" : {method} Katushai Challenge - Beat Killian: Progressive Pyros Stun Resist
"Katushai Challenge" : {method} Katushai Challenge - Beat Marissa: Progressive Electra ARM Power
"Katushai Challenge" : {method} Katushai Challenge - Beat Nathaniel: Progressive Gargoyle LEG Power
"Katushai Challenge" : {method} Katushai Challenge - Beat Ariel: Progressive Thorn ARM Speed
"Katushai Challenge" : {method} Katushai Challenge - Beat Eva O'Ryan: Progressive Chronos LEG Speed
"Katushai Challenge" : {method} Katushai Challenge - Beat Jacob: Progressive Gargoyle Armor
"Katushai Challenge" : {method} Katushai Challenge - Beat James: Progressive Jaguar LEG Speed
"Katushai Challenge" : {method} Katushai Challenge - Beat Steffan: Progressive Shredder LEG Speed
"Katushai Challenge" : {method} Win Katushai Challenge: Progressive Nova ARM Power
class "WAR Invitational" #00FF00
"WAR Invitational" : {method} WAR Invitational - Beat Nicoli: Progressive Thorn LEG Power
"WAR Invitational" : {method} WAR Invitational - Beat Bruce: Progressive Thorn Stun Resist
"WAR Invitational" : {method} WAR Invitational - Beat Selenna: Progressive Nova ARM Speed
"WAR Invitational" : {method} WAR Invitational - Beat Crystal: Money (Large)
"WAR Invitational" : {method} WAR Invitational - Beat Jahrod: Progressive Agility
"WAR Invitational" : {method} WAR Invitational - Beat Marissa: Progressive Electra Stun Resist
"WAR Invitational" : {method} WAR Invitational - Beat Christian: Progressive Thorn ARM Power
"WAR Invitational" : {method} WAR Invitational - Beat Rolland: Progressive Jaguar ARM Power
"WAR Invitational" : {method} WAR Invitational - Beat Scarlet: Progressive Thorn Enhancement
"WAR Invitational" : {method} WAR Invitational - Beat Milano: Progressive Chronos LEG Power
"WAR Invitational" : {method} WAR Invitational - Beat Veronica: Progressive Thorn Stun Resist
"WAR Invitational" : {method} Win WAR Invitational: Progressive Electra Enhancement
class "World Championship" #00FF00
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Ian Tavares: Progressive Jaguar LEG Speed
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Jaqouline: Progressive Gargoyle ARM Power
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Bruce: Progressive Gargoyle LEG Power
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Prince Vassar: Progressive Electra ARM Speed
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Selenna: Progressive Pyros LEG Power
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Jahrod: Progressive Flail ARM Power
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Raven: Progressive Nova Stun Resist
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Steel Claw: Progressive Gargoyle Armor
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Jack: Progressive Katana LEG Power
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Christian: Progressive Electra LEG Power
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Crystal: Progressive Chronos ARM Speed
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Rolland: Progressive Flail Enhancement
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Eva O'Ryan: Progressive Nova Armor
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Killian: Progressive Jaguar Stun Resist
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Marissa: Progressive Electra LEG Speed
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Ibrahim: Progressive Katana Stun Resist
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Scarlet: Progressive Jaguar ARM Power
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Milano: Progressive Thorn LEG Power
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Nathaniel: Progressive Thorn LEG Power
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Veronica: Progressive Jaguar LEG Speed
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Ariel: **Katana Unlock**
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Dr Lynn Yarr: Progressive Endurance
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Shirro: Progressive Jaguar Armor
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Jacob: Progressive Endurance
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Jean Paul: Progressive Chronos ARM Speed
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat James: Progressive Shredder LEG Power
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Steffan: Progressive Gargoyle ARM Speed
"World Championship" : {method} <&lock-unlocked,color=transparent> World Championship - Beat Cossette: Progressive Pyros LEG Speed
"World Championship" : {method} <&lock-unlocked,color=transparent> Win World Championship: Progressive Jaguar ARM Power
"World Championship" : {method} <&lock-locked> //Victory//: //**Victory**//
class "Jaguar Mechlab" #00FF00
"Jaguar Mechlab" : {method} Buy Jaguar ARM Power Upgrade 1: Progressive Jaguar ARM Power
"Jaguar Mechlab" : {method} Buy Jaguar ARM Power Upgrade 2: Progressive Flail ARM Speed
"Jaguar Mechlab" : {method} Buy Jaguar ARM Power Upgrade 3: Progressive Pyros LEG Speed
"Jaguar Mechlab" : {method} Buy Jaguar ARM Power Upgrade 4: Progressive Electra Armor
"Jaguar Mechlab" : {method} Buy Jaguar ARM Power Upgrade 5: Progressive Nova LEG Power
"Jaguar Mechlab" : {method} Buy Jaguar ARM Power Upgrade 6: Progressive Jaguar Stun Resist
"Jaguar Mechlab" : {method} Buy Jaguar ARM Power Upgrade 7: Progressive Electra Stun Resist
"Jaguar Mechlab" : {method} Buy Jaguar ARM Power Upgrade 8: Progressive Shadow ARM Speed
"Jaguar Mechlab" : {method} Buy Jaguar ARM Power Upgrade 9: Progressive Shredder Stun Resist
"Jaguar Mechlab" : {method} Buy Jaguar LEG Power Upgrade 1: Progressive Chronos Armor
"Jaguar Mechlab" : {method} Buy Jaguar LEG Power Upgrade 2: Progressive Jaguar LEG Power
"Jaguar Mechlab" : {method} Buy Jaguar LEG Power Upgrade 3: Progressive Flail Stun Resist
"Jaguar Mechlab" : {method} Buy Jaguar LEG Power Upgrade 4: Progressive Jaguar LEG Speed
"Jaguar Mechlab" : {method} Buy Jaguar LEG Power Upgrade 5: Progressive Shadow LEG Power
"Jaguar Mechlab" : {method} Buy Jaguar LEG Power Upgrade 6: Progressive Pyros Enhancement
"Jaguar Mechlab" : {method} Buy Jaguar LEG Power Upgrade 7: Progressive Katana ARM Speed
"Jaguar Mechlab" : {method} Buy Jaguar LEG Power Upgrade 8: Progressive Pyros Stun Resist
"Jaguar Mechlab" : {method} Buy Jaguar LEG Power Upgrade 9: Progressive Shadow ARM Speed
"Jaguar Mechlab" : {method} Buy Jaguar ARM Speed Upgrade 1: Progressive Gargoyle ARM Power
"Jaguar Mechlab" : {method} Buy Jaguar ARM Speed Upgrade 2: Progressive Shredder Armor
"Jaguar Mechlab" : {method} Buy Jaguar ARM Speed Upgrade 3: Progressive Power
"Jaguar Mechlab" : {method} Buy Jaguar ARM Speed Upgrade 4: Nothing
"Jaguar Mechlab" : {method} Buy Jaguar ARM Speed Upgrade 5: Progressive Jaguar ARM Speed
"Jaguar Mechlab" : {method} Buy Jaguar ARM Speed Upgrade 6: Progressive Shadow LEG Power
"Jaguar Mechlab" : {method} Buy Jaguar ARM Speed Upgrade 7: Progressive Pyros ARM Power
"Jaguar Mechlab" : {method} Buy Jaguar ARM Speed Upgrade 8: Progressive Gargoyle LEG Speed
"Jaguar Mechlab" : {method} Buy Jaguar ARM Speed Upgrade 9: Progressive Katana ARM Power
"Jaguar Mechlab" : {method} Buy Jaguar LEG Speed Upgrade 1: Progressive Agility
"Jaguar Mechlab" : {method} Buy Jaguar LEG Speed Upgrade 2: Progressive Thorn Stun Resist
"Jaguar Mechlab" : {method} Buy Jaguar LEG Speed Upgrade 3: Progressive Jaguar ARM Speed
"Jaguar Mechlab" : {method} Buy Jaguar LEG Speed Upgrade 4: Progressive Agility
"Jaguar Mechlab" : {method} Buy Jaguar LEG Speed Upgrade 5: Progressive Shadow ARM Power
"Jaguar Mechlab" : {method} Buy Jaguar LEG Speed Upgrade 6: Progressive Power
"Jaguar Mechlab" : {method} Buy Jaguar LEG Speed Upgrade 7: Progressive Thorn ARM Speed
"Jaguar Mechlab" : {method} Buy Jaguar LEG Speed Upgrade 8: Progressive Electra ARM Power
"Jaguar Mechlab" : {method} Buy Jaguar LEG Speed Upgrade 9: Progressive Chronos ARM Speed
"Jaguar Mechlab" : {method} Buy Jaguar Armor Upgrade 1: Progressive Electra ARM Speed
"Jaguar Mechlab" : {method} Buy Jaguar Armor Upgrade 2: Progressive Gargoyle LEG Speed
"Jaguar Mechlab" : {method} Buy Jaguar Armor Upgrade 3: Progressive Thorn ARM Power
"Jaguar Mechlab" : {method} Buy Jaguar Armor Upgrade 4: Progressive Electra ARM Power
"Jaguar Mechlab" : {method} Buy Jaguar Armor Upgrade 5: Progressive Pyros ARM Power
"Jaguar Mechlab" : {method} Buy Jaguar Armor Upgrade 6: Progressive Jaguar ARM Speed
"Jaguar Mechlab" : {method} Buy Jaguar Armor Upgrade 7: Progressive Flail Stun Resist
"Jaguar Mechlab" : {method} Buy Jaguar Armor Upgrade 8: Progressive Shadow Stun Resist
"Jaguar Mechlab" : {method} Buy Jaguar Armor Upgrade 9: Progressive Pyros Stun Resist
"Jaguar Mechlab" : {method} Buy Jaguar Stun Resist Upgrade 1: Progressive Endurance
"Jaguar Mechlab" : {method} Buy Jaguar Stun Resist Upgrade 2: Progressive Endurance
"Jaguar Mechlab" : {method} Buy Jaguar Stun Resist Upgrade 3: Progressive Shadow Armor
"Jaguar Mechlab" : {method} Buy Jaguar Stun Resist Upgrade 4: Progressive Power
"Jaguar Mechlab" : {method} Buy Jaguar Stun Resist Upgrade 5: Progressive Agility
"Jaguar Mechlab" : {method} Buy Jaguar Stun Resist Upgrade 6: Progressive Jaguar LEG Power
"Jaguar Mechlab" : {method} Buy Jaguar Stun Resist Upgrade 7: Progressive Electra Armor
"Jaguar Mechlab" : {method} Buy Jaguar Stun Resist Upgrade 8: Progressive Endurance
"Jaguar Mechlab" : {method} Buy Jaguar Stun Resist Upgrade 9: Progressive Chronos ARM Power
class "Shadow Mechlab" #00FF00
"Shadow Mechlab" : {method} Buy Shadow ARM Power Upgrade 1: Progressive Pyros LEG Power
"Shadow Mechlab" : {method} Buy Shadow ARM Power Upgrade 2: Progressive Thorn LEG Speed
"Shadow Mechlab" : {method} Buy Shadow ARM Power Upgrade 3: Progressive Gargoyle Stun Resist
"Shadow Mechlab" : {method} Buy Shadow ARM Power Upgrade 4: Progressive Chronos Stun Resist
"Shadow Mechlab" : {method} Buy Shadow ARM Power Upgrade 5: Progressive Katana ARM Speed
"Shadow Mechlab" : {method} Buy Shadow ARM Power Upgrade 6: Progressive Gargoyle LEG Speed
"Shadow Mechlab" : {method} Buy Shadow ARM Power Upgrade 7: Progressive Endurance
"Shadow Mechlab" : {method} Buy Shadow ARM Power Upgrade 8: Progressive Shredder Enhancement
"Shadow Mechlab" : {method} Buy Shadow ARM Power Upgrade 9: Progressive Katana Enhancement
"Shadow Mechlab" : {method} Buy Shadow LEG Power Upgrade 1: Progressive Thorn Armor
"Shadow Mechlab" : {method} Buy Shadow LEG Power Upgrade 2: Progressive Gargoyle LEG Speed
"Shadow Mechlab" : {method} Buy Shadow LEG Power Upgrade 3: Progressive Chronos Armor
"Shadow Mechlab" : {method} Buy Shadow LEG Power Upgrade 4: Progressive Chronos Armor
"Shadow Mechlab" : {method} Buy Shadow LEG Power Upgrade 5: Progressive Gargoyle ARM Power
"Shadow Mechlab" : {method} Buy Shadow LEG Power Upgrade 6: Progressive Chronos ARM Speed
"Shadow Mechlab" : {method} Buy Shadow LEG Power Upgrade 7: Progressive Shredder ARM Power
"Shadow Mechlab" : {method} Buy Shadow LEG Power Upgrade 8: Progressive Shredder ARM Power
"Shadow Mechlab" : {method} Buy Shadow LEG Power Upgrade 9: Progressive Agility
"Shadow Mechlab" : {method} Buy Shadow ARM Speed Upgrade 1: Progressive Shadow LEG Speed
"Shadow Mechlab" : {method} Buy Shadow ARM Speed Upgrade 2: Progressive Pyros ARM Power
"Shadow Mechlab" : {method} Buy Shadow ARM Speed Upgrade 3: Progressive Electra LEG Power
"Shadow Mechlab" : {method} Buy Shadow ARM Speed Upgrade 4: Progressive Power
"Shadow Mechlab" : {method} Buy Shadow ARM Speed Upgrade 5: Progressive Chronos Stun Resist
"Shadow Mechlab" : {method} Buy Shadow ARM Speed Upgrade 6: Progressive Electra LEG Power
"Shadow Mechlab" : {method} Buy Shadow ARM Speed Upgrade 7: Progressive Flail LEG Power
"Shadow Mechlab" : {method} Buy Shadow ARM Speed Upgrade 8: Progressive Katana Stun Resist
"Shadow Mechlab" : {method} Buy Shadow ARM Speed Upgrade 9: Progressive Chronos ARM Power
"Shadow Mechlab" : {method} Buy Shadow LEG Speed Upgrade 1: Progressive Shadow LEG Power
"Shadow Mechlab" : {method} Buy Shadow LEG Speed Upgrade 2: Progressive Shredder ARM Speed
"Shadow Mechlab" : {method} Buy Shadow LEG Speed Upgrade 3: Progressive Chronos ARM Speed
"Shadow Mechlab" : {method} Buy Shadow LEG Speed Upgrade 4: Progressive Gargoyle ARM Speed
"Shadow Mechlab" : {method} Buy Shadow LEG Speed Upgrade 5: Progressive Jaguar LEG Speed
"Shadow Mechlab" : {method} Buy Shadow LEG Speed Upgrade 6: Progressive Agility
"Shadow Mechlab" : {method} Buy Shadow LEG Speed Upgrade 7: Progressive Pyros Armor
"Shadow Mechlab" : {method} Buy Shadow LEG Speed Upgrade 8: Progressive Electra Stun Resist
"Shadow Mechlab" : {method} Buy Shadow LEG Speed Upgrade 9: Progressive Pyros Armor
"Shadow Mechlab" : {method} Buy Shadow Armor Upgrade 1: Progressive Katana Armor
"Shadow Mechlab" : {method} Buy Shadow Armor Upgrade 2: Progressive Chronos Armor
"Shadow Mechlab" : {method} Buy Shadow Armor Upgrade 3: Progressive Shredder ARM Power
"Shadow Mechlab" : {method} Buy Shadow Armor Upgrade 4: Progressive Nova LEG Speed
"Shadow Mechlab" : {method} Buy Shadow Armor Upgrade 5: Progressive Electra LEG Power
"Shadow Mechlab" : {method} Buy Shadow Armor Upgrade 6: Progressive Nova ARM Power
"Shadow Mechlab" : {method} Buy Shadow Armor Upgrade 7: Money (Small)
"Shadow Mechlab" : {method} Buy Shadow Armor Upgrade 8: Progressive Flail Stun Resist
"Shadow Mechlab" : {method} Buy Shadow Armor Upgrade 9: Progressive Electra Stun Resist
"Shadow Mechlab" : {method} Buy Shadow Stun Resist Upgrade 1: Progressive Shredder Stun Resist
"Shadow Mechlab" : {method} Buy Shadow Stun Resist Upgrade 2: Progressive Thorn ARM Power
"Shadow Mechlab" : {method} Buy Shadow Stun Resist Upgrade 3: Progressive Flail LEG Speed
"Shadow Mechlab" : {method} Buy Shadow Stun Resist Upgrade 4: Progressive Pyros LEG Power
"Shadow Mechlab" : {method} Buy Shadow Stun Resist Upgrade 5: Progressive Katana Stun Resist
"Shadow Mechlab" : {method} Buy Shadow Stun Resist Upgrade 6: Progressive Electra LEG Power
"Shadow Mechlab" : {method} Buy Shadow Stun Resist Upgrade 7: Progressive Electra Armor
"Shadow Mechlab" : {method} Buy Shadow Stun Resist Upgrade 8: Progressive Katana Armor
"Shadow Mechlab" : {method} Buy Shadow Stun Resist Upgrade 9: Progressive Gargoyle LEG Power
class "Thorn Mechlab" #00FF00
"Thorn Mechlab" : {method} Buy Thorn ARM Power Upgrade 1: Progressive Katana Stun Resist
"Thorn Mechlab" : {method} Buy Thorn ARM Power Upgrade 2: Progressive Endurance
"Thorn Mechlab" : {method} Buy Thorn ARM Power Upgrade 3: Progressive Electra LEG Power
"Thorn Mechlab" : {method} Buy Thorn ARM Power Upgrade 4: Progressive Thorn LEG Speed
"Thorn Mechlab" : {method} Buy Thorn ARM Power Upgrade 5: Money (Small)
"Thorn Mechlab" : {method} Buy Thorn ARM Power Upgrade 6: Progressive Thorn ARM Power
"Thorn Mechlab" : {method} Buy Thorn ARM Power Upgrade 7: Progressive Jaguar Armor
"Thorn Mechlab" : {method} Buy Thorn ARM Power Upgrade 8: Progressive Endurance
"Thorn Mechlab" : {method} Buy Thorn ARM Power Upgrade 9: Progressive Thorn LEG Speed
"Thorn Mechlab" : {method} Buy Thorn LEG Power Upgrade 1: Progressive Shadow LEG Speed
"Thorn Mechlab" : {method} Buy Thorn LEG Power Upgrade 2: Progressive Nova LEG Speed
"Thorn Mechlab" : {method} Buy Thorn LEG Power Upgrade 3: Progressive Thorn Stun Resist
"Thorn Mechlab" : {method} Buy Thorn LEG Power Upgrade 4: Progressive Jaguar Armor
"Thorn Mechlab" : {method} Buy Thorn LEG Power Upgrade 5: Progressive Shadow Stun Resist
"Thorn Mechlab" : {method} Buy Thorn LEG Power Upgrade 6: Progressive Electra ARM Speed
"Thorn Mechlab" : {method} Buy Thorn LEG Power Upgrade 7: Progressive Thorn Armor
"Thorn Mechlab" : {method} Buy Thorn LEG Power Upgrade 8: Progressive Gargoyle LEG Power
"Thorn Mechlab" : {method} Buy Thorn LEG Power Upgrade 9: Progressive Katana LEG Power
"Thorn Mechlab" : {method} Buy Thorn ARM Speed Upgrade 1: Progressive Endurance
"Thorn Mechlab" : {method} Buy Thorn ARM Speed Upgrade 2: Progressive Shredder LEG Speed
"Thorn Mechlab" : {method} Buy Thorn ARM Speed Upgrade 3: Progressive Electra ARM Speed
"Thorn Mechlab" : {method} Buy Thorn ARM Speed Upgrade 4: Progressive Jaguar ARM Power
"Thorn Mechlab" : {method} Buy Thorn ARM Speed Upgrade 5: Progressive Gargoyle ARM Speed
"Thorn Mechlab" : {method} Buy Thorn ARM Speed Upgrade 6: Progressive Nova ARM Power
"Thorn Mechlab" : {method} Buy Thorn ARM Speed Upgrade 7: Progressive Flail ARM Speed
"Thorn Mechlab" : {method} Buy Thorn ARM Speed Upgrade 8: Progressive Flail LEG Power
"Thorn Mechlab" : {method} Buy Thorn ARM Speed Upgrade 9: Progressive Katana ARM Power
"Thorn Mechlab" : {method} Buy Thorn LEG Speed Upgrade 1: Nothing
"Thorn Mechlab" : {method} Buy Thorn LEG Speed Upgrade 2: Progressive Pyros Stun Resist
"Thorn Mechlab" : {method} Buy Thorn LEG Speed Upgrade 3: Progressive Chronos ARM Power
"Thorn Mechlab" : {method} Buy Thorn LEG Speed Upgrade 4: Progressive Katana LEG Power
"Thorn Mechlab" : {method} Buy Thorn LEG Speed Upgrade 5: Progressive Shadow ARM Speed
"Thorn Mechlab" : {method} Buy Thorn LEG Speed Upgrade 6: Progressive Shredder ARM Speed
"Thorn Mechlab" : {method} Buy Thorn LEG Speed Upgrade 7: Progressive Electra ARM Power
"Thorn Mechlab" : {method} Buy Thorn LEG Speed Upgrade 8: Progressive Electra ARM Speed
"Thorn Mechlab" : {method} Buy Thorn LEG Speed Upgrade 9: Money (Small)
"Thorn Mechlab" : {method} Buy Thorn Armor Upgrade 1: Progressive Endurance
"Thorn Mechlab" : {method} Buy Thorn Armor Upgrade 2: Progressive Endurance
"Thorn Mechlab" : {method} Buy Thorn Armor Upgrade 3: Progressive Nova LEG Power
"Thorn Mechlab" : {method} Buy Thorn Armor Upgrade 4: Progressive Nova Stun Resist
"Thorn Mechlab" : {method} Buy Thorn Armor Upgrade 5: Progressive Agility
"Thorn Mechlab" : {method} Buy Thorn Armor Upgrade 6: Progressive Shredder Stun Resist
"Thorn Mechlab" : {method} Buy Thorn Armor Upgrade 7: Progressive Pyros Armor
"Thorn Mechlab" : {method} Buy Thorn Armor Upgrade 8: Progressive Katana Enhancement
"Thorn Mechlab" : {method} Buy Thorn Armor Upgrade 9: Money (Large)
"Thorn Mechlab" : {method} Buy Thorn Stun Resist Upgrade 1: Progressive Nova ARM Speed
"Thorn Mechlab" : {method} Buy Thorn Stun Resist Upgrade 2: Progressive Nova LEG Speed
"Thorn Mechlab" : {method} Buy Thorn Stun Resist Upgrade 3: Progressive Gargoyle Stun Resist
"Thorn Mechlab" : {method} Buy Thorn Stun Resist Upgrade 4: Progressive Flail Armor
"Thorn Mechlab" : {method} Buy Thorn Stun Resist Upgrade 5: Progressive Flail ARM Power
"Thorn Mechlab" : {method} Buy Thorn Stun Resist Upgrade 6: Progressive Flail Armor
"Thorn Mechlab" : {method} Buy Thorn Stun Resist Upgrade 7: Progressive Shredder LEG Speed
"Thorn Mechlab" : {method} Buy Thorn Stun Resist Upgrade 8: Progressive Flail Stun Resist
"Thorn Mechlab" : {method} Buy Thorn Stun Resist Upgrade 9: Progressive Power
class "Pyros Mechlab" #00FF00
"Pyros Mechlab" : {method} Buy Pyros ARM Power Upgrade 1: Progressive Thorn ARM Power
"Pyros Mechlab" : {method} Buy Pyros ARM Power Upgrade 2: **Electra Unlock**
"Pyros Mechlab" : {method} Buy Pyros ARM Power Upgrade 3: **Jaguar Unlock**
"Pyros Mechlab" : {method} Buy Pyros ARM Power Upgrade 4: Progressive Shadow ARM Power
"Pyros Mechlab" : {method} Buy Pyros ARM Power Upgrade 5: Progressive Gargoyle ARM Power
"Pyros Mechlab" : {method} Buy Pyros ARM Power Upgrade 6: Progressive Chronos ARM Power
"Pyros Mechlab" : {method} Buy Pyros ARM Power Upgrade 7: Progressive Thorn LEG Power
"Pyros Mechlab" : {method} Buy Pyros ARM Power Upgrade 8: Progressive Gargoyle LEG Speed
"Pyros Mechlab" : {method} Buy Pyros ARM Power Upgrade 9: Progressive Shredder LEG Power
"Pyros Mechlab" : {method} Buy Pyros LEG Power Upgrade 1: Progressive Pyros LEG Power
"Pyros Mechlab" : {method} Buy Pyros LEG Power Upgrade 2: Progressive Electra ARM Speed
"Pyros Mechlab" : {method} Buy Pyros LEG Power Upgrade 3: Progressive Jaguar ARM Power
"Pyros Mechlab" : {method} Buy Pyros LEG Power Upgrade 4: Progressive Shadow ARM Power
"Pyros Mechlab" : {method} Buy Pyros LEG Power Upgrade 5: Progressive Power
"Pyros Mechlab" : {method} Buy Pyros LEG Power Upgrade 6: Progressive Shadow ARM Speed
"Pyros Mechlab" : {method} Buy Pyros LEG Power Upgrade 7: Nothing
"Pyros Mechlab" : {method} Buy Pyros LEG Power Upgrade 8: Progressive Pyros ARM Speed
"Pyros Mechlab" : {method} Buy Pyros LEG Power Upgrade 9: Progressive Shredder ARM Power
"Pyros Mechlab" : {method} Buy Pyros ARM Speed Upgrade 1: Progressive Shadow Armor
"Pyros Mechlab" : {method} Buy Pyros ARM Speed Upgrade 2: Progressive Thorn ARM Power
"Pyros Mechlab" : {method} Buy Pyros ARM Speed Upgrade 3: Progressive Shredder ARM Power
"Pyros Mechlab" : {method} Buy Pyros ARM Speed Upgrade 4: Progressive Jaguar Stun Resist
"Pyros Mechlab" : {method} Buy Pyros ARM Speed Upgrade 5: Progressive Shredder Stun Resist
"Pyros Mechlab" : {method} Buy Pyros ARM Speed Upgrade 6: Progressive Thorn LEG Power
"Pyros Mechlab" : {method} Buy Pyros ARM Speed Upgrade 7: Progressive Electra LEG Speed
"Pyros Mechlab" : {method} Buy Pyros ARM Speed Upgrade 8: Progressive Shredder LEG Speed
"Pyros Mechlab" : {method} Buy Pyros ARM Speed Upgrade 9: Progressive Agility
"Pyros Mechlab" : {method} Buy Pyros LEG Speed Upgrade 1: Progressive Shadow LEG Power
"Pyros Mechlab" : {method} Buy Pyros LEG Speed Upgrade 2: Progressive Katana ARM Power
"Pyros Mechlab" : {method} Buy Pyros LEG Speed Upgrade 3: Progressive Shredder LEG Power
"Pyros Mechlab" : {method} Buy Pyros LEG Speed Upgrade 4: Progressive Power
"Pyros Mechlab" : {method} Buy Pyros LEG Speed Upgrade 5: Progressive Power
"Pyros Mechlab" : {method} Buy Pyros LEG Speed Upgrade 6: Progressive Nova ARM Speed
"Pyros Mechlab" : {method} Buy Pyros LEG Speed Upgrade 7: Progressive Nova Stun Resist
"Pyros Mechlab" : {method} Buy Pyros LEG Speed Upgrade 8: Money (Large)
"Pyros Mechlab" : {method} Buy Pyros LEG Speed Upgrade 9: Progressive Gargoyle ARM Speed
"Pyros Mechlab" : {method} Buy Pyros Armor Upgrade 1: Progressive Shredder LEG Power
"Pyros Mechlab" : {method} Buy Pyros Armor Upgrade 2: Progressive Electra Enhancement
"Pyros Mechlab" : {method} Buy Pyros Armor Upgrade 3: Progressive Chronos Stun Resist
"Pyros Mechlab" : {method} Buy Pyros Armor Upgrade 4: Progressive Shredder ARM Power
"Pyros Mechlab" : {method} Buy Pyros Armor Upgrade 5: Progressive Endurance
"Pyros Mechlab" : {method} Buy Pyros Armor Upgrade 6: Progressive Electra LEG Speed
"Pyros Mechlab" : {method} Buy Pyros Armor Upgrade 7: Progressive Thorn ARM Speed
"Pyros Mechlab" : {method} Buy Pyros Armor Upgrade 8: Progressive Electra Armor
"Pyros Mechlab" : {method} Buy Pyros Armor Upgrade 9: Progressive Pyros Stun Resist
"Pyros Mechlab" : {method} Buy Pyros Stun Resist Upgrade 1: **Thorn Unlock**
"Pyros Mechlab" : {method} Buy Pyros Stun Resist Upgrade 2: Progressive Nova LEG Power
"Pyros Mechlab" : {method} Buy Pyros Stun Resist Upgrade 3: Progressive Agility
"Pyros Mechlab" : {method} Buy Pyros Stun Resist Upgrade 4: Progressive Flail ARM Speed
"Pyros Mechlab" : {method} Buy Pyros Stun Resist Upgrade 5: Progressive Shadow Armor
"Pyros Mechlab" : {method} Buy Pyros Stun Resist Upgrade 6: Progressive Power
"Pyros Mechlab" : {method} Buy Pyros Stun Resist Upgrade 7: Progressive Chronos LEG Power
"Pyros Mechlab" : {method} Buy Pyros Stun Resist Upgrade 8: Progressive Pyros Stun Resist
"Pyros Mechlab" : {method} Buy Pyros Stun Resist Upgrade 9: Progressive Endurance
class "Electra Mechlab" #00FF00
"Electra Mechlab" : {method} Buy Electra ARM Power Upgrade 1: Progressive Agility
"Electra Mechlab" : {method} Buy Electra ARM Power Upgrade 2: Progressive Shredder Stun Resist
"Electra Mechlab" : {method} Buy Electra ARM Power Upgrade 3: Progressive Nova Armor
"Electra Mechlab" : {method} Buy Electra ARM Power Upgrade 4: Progressive Thorn LEG Speed
"Electra Mechlab" : {method} Buy Electra ARM Power Upgrade 5: Progressive Katana ARM Power
"Electra Mechlab" : {method} Buy Electra ARM Power Upgrade 6: Progressive Nova Stun Resist
"Electra Mechlab" : {method} Buy Electra ARM Power Upgrade 7: Progressive Katana LEG Power
"Electra Mechlab" : {method} Buy Electra ARM Power Upgrade 8: Progressive Katana Armor
"Electra Mechlab" : {method} Buy Electra ARM Power Upgrade 9: Progressive Shadow ARM Speed
"Electra Mechlab" : {method} Buy Electra LEG Power Upgrade 1: Progressive Shadow LEG Speed
"Electra Mechlab" : {method} Buy Electra LEG Power Upgrade 2: Progressive Pyros LEG Power
"Electra Mechlab" : {method} Buy Electra LEG Power Upgrade 3: Progressive Flail Stun Resist
"Electra Mechlab" : {method} Buy Electra LEG Power Upgrade 4: Progressive Katana LEG Speed
"Electra Mechlab" : {method} Buy Electra LEG Power Upgrade 5: Progressive Shredder ARM Power
"Electra Mechlab" : {method} Buy Electra LEG Power Upgrade 6: Progressive Pyros Stun Resist
"Electra Mechlab" : {method} Buy Electra LEG Power Upgrade 7: Progressive Nova ARM Power
"Electra Mechlab" : {method} Buy Electra LEG Power Upgrade 8: Progressive Chronos ARM Speed
"Electra Mechlab" : {method} Buy Electra LEG Power Upgrade 9: Progressive Shadow ARM Speed
"Electra Mechlab" : {method} Buy Electra ARM Speed Upgrade 1: Progressive Shadow ARM Power
"Electra Mechlab" : {method} Buy Electra ARM Speed Upgrade 2: Progressive Shadow ARM Speed
"Electra Mechlab" : {method} Buy Electra ARM Speed Upgrade 3: Money (Large)
"Electra Mechlab" : {method} Buy Electra ARM Speed Upgrade 4: Progressive Shadow LEG Speed
"Electra Mechlab" : {method} Buy Electra ARM Speed Upgrade 5: Progressive Flail Stun Resist
"Electra Mechlab" : {method} Buy Electra ARM Speed Upgrade 6: Progressive Flail ARM Speed
"Electra Mechlab" : {method} Buy Electra ARM Speed Upgrade 7: Money (Small)
"Electra Mechlab" : {method} Buy Electra ARM Speed Upgrade 8: Progressive Chronos ARM Power
"Electra Mechlab" : {method} Buy Electra ARM Speed Upgrade 9: Nothing
"Electra Mechlab" : {method} Buy Electra LEG Speed Upgrade 1: Progressive Gargoyle ARM Speed
"Electra Mechlab" : {method} Buy Electra LEG Speed Upgrade 2: Progressive Katana ARM Power
"Electra Mechlab" : {method} Buy Electra LEG Speed Upgrade 3: Progressive Katana Armor
"Electra Mechlab" : {method} Buy Electra LEG Speed Upgrade 4: Progressive Endurance
"Electra Mechlab" : {method} Buy Electra LEG Speed Upgrade 5: Progressive Electra LEG Speed
"Electra Mechlab" : {method} Buy Electra LEG Speed Upgrade 6: Progressive Gargoyle Armor
"Electra Mechlab" : {method} Buy Electra LEG Speed Upgrade 7: Progressive Jaguar Armor
"Electra Mechlab" : {method} Buy Electra LEG Speed Upgrade 8: Progressive Agility
"Electra Mechlab" : {method} Buy Electra LEG Speed Upgrade 9: Progressive Nova ARM Power
"Electra Mechlab" : {method} Buy Electra Armor Upgrade 1: Progressive Shredder Armor
"Electra Mechlab" : {method} Buy Electra Armor Upgrade 2: Progressive Katana Armor
"Electra Mechlab" : {method} Buy Electra Armor Upgrade 3: Progressive Chronos Stun Resist
"Electra Mechlab" : {method} Buy Electra Armor Upgrade 4: Progressive Thorn Enhancement
"Electra Mechlab" : {method} Buy Electra Armor Upgrade 5: Nothing
"Electra Mechlab" : {method} Buy Electra Armor Upgrade 6: Progressive Gargoyle Armor
"Electra Mechlab" : {method} Buy Electra Armor Upgrade 7: Progressive Gargoyle Enhancement
"Electra Mechlab" : {method} Buy Electra Armor Upgrade 8: Progressive Agility
"Electra Mechlab" : {method} Buy Electra Armor Upgrade 9: Progressive Flail LEG Power
"Electra Mechlab" : {method} Buy Electra Stun Resist Upgrade 1: Progressive Nova Stun Resist
"Electra Mechlab" : {method} Buy Electra Stun Resist Upgrade 2: Progressive Gargoyle Armor
"Electra Mechlab" : {method} Buy Electra Stun Resist Upgrade 3: Progressive Chronos LEG Speed
"Electra Mechlab" : {method} Buy Electra Stun Resist Upgrade 4: Progressive Katana Enhancement
"Electra Mechlab" : {method} Buy Electra Stun Resist Upgrade 5: Progressive Pyros ARM Speed
"Electra Mechlab" : {method} Buy Electra Stun Resist Upgrade 6: Progressive Nova LEG Speed
"Electra Mechlab" : {method} Buy Electra Stun Resist Upgrade 7: Progressive Jaguar LEG Speed
"Electra Mechlab" : {method} Buy Electra Stun Resist Upgrade 8: Progressive Jaguar ARM Power
"Electra Mechlab" : {method} Buy Electra Stun Resist Upgrade 9: Progressive Shredder Armor
class "Katana Mechlab" #00FF00
"Katana Mechlab" : {method} Buy Katana ARM Power Upgrade 1: Progressive Jaguar Armor
"Katana Mechlab" : {method} Buy Katana ARM Power Upgrade 2: Progressive Nova LEG Power
"Katana Mechlab" : {method} Buy Katana ARM Power Upgrade 3: Progressive Gargoyle LEG Power
"Katana Mechlab" : {method} Buy Katana ARM Power Upgrade 4: Progressive Power
"Katana Mechlab" : {method} Buy Katana ARM Power Upgrade 5: Progressive Nova ARM Speed
"Katana Mechlab" : {method} Buy Katana ARM Power Upgrade 6: **Nova Unlock**
"Katana Mechlab" : {method} Buy Katana ARM Power Upgrade 7: Progressive Pyros LEG Speed
"Katana Mechlab" : {method} Buy Katana ARM Power Upgrade 8: Progressive Katana ARM Speed
"Katana Mechlab" : {method} Buy Katana ARM Power Upgrade 9: Progressive Shadow Enhancement
"Katana Mechlab" : {method} Buy Katana LEG Power Upgrade 1: Progressive Jaguar ARM Speed
"Katana Mechlab" : {method} Buy Katana LEG Power Upgrade 2: Progressive Katana ARM Power
"Katana Mechlab" : {method} Buy Katana LEG Power Upgrade 3: Progressive Agility
"Katana Mechlab" : {method} Buy Katana LEG Power Upgrade 4: Progressive Shredder LEG Speed
"Katana Mechlab" : {method} Buy Katana LEG Power Upgrade 5: Progressive Pyros LEG Speed
"Katana Mechlab" : {method} Buy Katana LEG Power Upgrade 6: Money (Small)
"Katana Mechlab" : {method} Buy Katana LEG Power Upgrade 7: Progressive Katana Stun Resist
"Katana Mechlab" : {method} Buy Katana LEG Power Upgrade 8: Progressive Nova Stun Resist
"Katana Mechlab" : {method} Buy Katana LEG Power Upgrade 9: Progressive Pyros ARM Speed
"Katana Mechlab" : {method} Buy Katana ARM Speed Upgrade 1: Money (Large)
"Katana Mechlab" : {method} Buy Katana ARM Speed Upgrade 2: Progressive Shadow Stun Resist
"Katana Mechlab" : {method} Buy Katana ARM Speed Upgrade 3: Nothing
"Katana Mechlab" : {method} Buy Katana ARM Speed Upgrade 4: Progressive Shredder LEG Power
"Katana Mechlab" : {method} Buy Katana ARM Speed Upgrade 5: Progressive Agility
"Katana Mechlab" : {method} Buy Katana ARM Speed Upgrade 6: Progressive Shadow Enhancement
"Katana Mechlab" : {method} Buy Katana ARM Speed Upgrade 7: Progressive Electra Armor
"Katana Mechlab" : {method} Buy Katana ARM Speed Upgrade 8: Progressive Thorn Armor
"Katana Mechlab" : {method} Buy Katana ARM Speed Upgrade 9: Progressive Gargoyle Armor
"Katana Mechlab" : {method} Buy Katana LEG Speed Upgrade 1: Progressive Nova LEG Speed
"Katana Mechlab" : {method} Buy Katana LEG Speed Upgrade 2: Progressive Shredder Armor
"Katana Mechlab" : {method} Buy Katana LEG Speed Upgrade 3: Progressive Electra ARM Power
"Katana Mechlab" : {method} Buy Katana LEG Speed Upgrade 4: Progressive Pyros Armor
"Katana Mechlab" : {method} Buy Katana LEG Speed Upgrade 5: Progressive Agility
"Katana Mechlab" : {method} Buy Katana LEG Speed Upgrade 6: Progressive Pyros LEG Power
"Katana Mechlab" : {method} Buy Katana LEG Speed Upgrade 7: Money (Small)
"Katana Mechlab" : {method} Buy Katana LEG Speed Upgrade 8: Progressive Katana LEG Power
"Katana Mechlab" : {method} Buy Katana LEG Speed Upgrade 9: Progressive Nova Stun Resist
"Katana Mechlab" : {method} Buy Katana Armor Upgrade 1: Progressive Shredder LEG Power
"Katana Mechlab" : {method} Buy Katana Armor Upgrade 2: Progressive Thorn LEG Power
"Katana Mechlab" : {method} Buy Katana Armor Upgrade 3: Progressive Nova LEG Power
"Katana Mechlab" : {method} Buy Katana Armor Upgrade 4: Progressive Pyros Stun Resist
"Katana Mechlab" : {method} Buy Katana Armor Upgrade 5: Progressive Gargoyle LEG Power
"Katana Mechlab" : {method} Buy Katana Armor Upgrade 6: Progressive Chronos Stun Resist
"Katana Mechlab" : {method} Buy Katana Armor Upgrade 7: Progressive Chronos LEG Speed
"Katana Mechlab" : {method} Buy Katana Armor Upgrade 8: Progressive Jaguar ARM Speed
"Katana Mechlab" : {method} Buy Katana Armor Upgrade 9: Progressive Flail LEG Speed
"Katana Mechlab" : {method} Buy Katana Stun Resist Upgrade 1: Progressive Katana LEG Power
"Katana Mechlab" : {method} Buy Katana Stun Resist Upgrade 2: Progressive Pyros ARM Power
"Katana Mechlab" : {method} Buy Katana Stun Resist Upgrade 3: Progressive Shadow LEG Power
"Katana Mechlab" : {method} Buy Katana Stun Resist Upgrade 4: Progressive Pyros LEG Power
"Katana Mechlab" : {method} Buy Katana Stun Resist Upgrade 5: Progressive Nova ARM Power
"Katana Mechlab" : {method} Buy Katana Stun Resist Upgrade 6: Progressive Thorn Stun Resist
"Katana Mechlab" : {method} Buy Katana Stun Resist Upgrade 7: Progressive Nova Armor
"Katana Mechlab" : {method} Buy Katana Stun Resist Upgrade 8: Progressive Chronos LEG Speed
"Katana Mechlab" : {method} Buy Katana Stun Resist Upgrade 9: Progressive Thorn LEG Power
class "Shredder Mechlab" #00FF00
"Shredder Mechlab" : {method} Buy Shredder ARM Power Upgrade 1: Progressive Chronos LEG Power
"Shredder Mechlab" : {method} Buy Shredder ARM Power Upgrade 2: Progressive Katana LEG Speed
"Shredder Mechlab" : {method} Buy Shredder ARM Power Upgrade 3: Progressive Nova ARM Speed
"Shredder Mechlab" : {method} Buy Shredder ARM Power Upgrade 4: Progressive Shredder Armor
"Shredder Mechlab" : {method} Buy Shredder ARM Power Upgrade 5: Progressive Flail LEG Power
"Shredder Mechlab" : {method} Buy Shredder ARM Power Upgrade 6: Progressive Nova ARM Speed
"Shredder Mechlab" : {method} Buy Shredder ARM Power Upgrade 7: Progressive Jaguar Armor
"Shredder Mechlab" : {method} Buy Shredder ARM Power Upgrade 8: Progressive Power
"Shredder Mechlab" : {method} Buy Shredder ARM Power Upgrade 9: Progressive Jaguar ARM Speed
"Shredder Mechlab" : {method} Buy Shredder LEG Power Upgrade 1: Progressive Katana ARM Power
"Shredder Mechlab" : {method} Buy Shredder LEG Power Upgrade 2: Progressive Gargoyle Armor
"Shredder Mechlab" : {method} Buy Shredder LEG Power Upgrade 3: Progressive Nova Armor
"Shredder Mechlab" : {method} Buy Shredder LEG Power Upgrade 4: Progressive Pyros ARM Speed
"Shredder Mechlab" : {method} Buy Shredder LEG Power Upgrade 5: Progressive Jaguar Stun Resist
"Shredder Mechlab" : {method} Buy Shredder LEG Power Upgrade 6: Progressive Pyros LEG Speed
"Shredder Mechlab" : {method} Buy Shredder LEG Power Upgrade 7: Progressive Thorn Stun Resist
"Shredder Mechlab" : {method} Buy Shredder LEG Power Upgrade 8: Progressive Power
"Shredder Mechlab" : {method} Buy Shredder LEG Power Upgrade 9: Progressive Katana ARM Power
"Shredder Mechlab" : {method} Buy Shredder ARM Speed Upgrade 1: Progressive Shadow LEG Power
"Shredder Mechlab" : {method} Buy Shredder ARM Speed Upgrade 2: Progressive Pyros Enhancement
"Shredder Mechlab" : {method} Buy Shredder ARM Speed Upgrade 3: Nothing
"Shredder Mechlab" : {method} Buy Shredder ARM Speed Upgrade 4: Progressive Thorn LEG Speed
"Shredder Mechlab" : {method} Buy Shredder ARM Speed Upgrade 5: Progressive Electra Armor
"Shredder Mechlab" : {method} Buy Shredder ARM Speed Upgrade 6: Progressive Thorn Stun Resist
"Shredder Mechlab" : {method} Buy Shredder ARM Speed Upgrade 7: Progressive Endurance
"Shredder Mechlab" : {method} Buy Shredder ARM Speed Upgrade 8: Progressive Katana LEG Speed
"Shredder Mechlab" : {method} Buy Shredder ARM Speed Upgrade 9: Progressive Nova ARM Speed
"Shredder Mechlab" : {method} Buy Shredder LEG Speed Upgrade 1: Progressive Power
"Shredder Mechlab" : {method} Buy Shredder LEG Speed Upgrade 2: Progressive Jaguar LEG Speed
"Shredder Mechlab" : {method} Buy Shredder LEG Speed Upgrade 3: Progressive Katana Armor
"Shredder Mechlab" : {method} Buy Shredder LEG Speed Upgrade 4: Progressive Electra ARM Speed
"Shredder Mechlab" : {method} Buy Shredder LEG Speed Upgrade 5: Progressive Flail LEG Power
"Shredder Mechlab" : {method} Buy Shredder LEG Speed Upgrade 6: Progressive Thorn ARM Power
"Shredder Mechlab" : {method} Buy Shredder LEG Speed Upgrade 7: Progressive Gargoyle Stun Resist
"Shredder Mechlab" : {method} Buy Shredder LEG Speed Upgrade 8: Progressive Thorn LEG Power
"Shredder Mechlab" : {method} Buy Shredder LEG Speed Upgrade 9: Progressive Jaguar LEG Power
"Shredder Mechlab" : {method} Buy Shredder Armor Upgrade 1: Progressive Shadow LEG Speed
"Shredder Mechlab" : {method} Buy Shredder Armor Upgrade 2: Progressive Chronos Stun Resist
"Shredder Mechlab" : {method} Buy Shredder Armor Upgrade 3: Progressive Chronos LEG Power
"Shredder Mechlab" : {method} Buy Shredder Armor Upgrade 4: Progressive Katana ARM Speed
"Shredder Mechlab" : {method} Buy Shredder Armor Upgrade 5: Progressive Shredder LEG Speed
"Shredder Mechlab" : {method} Buy Shredder Armor Upgrade 6: Progressive Katana Stun Resist
"Shredder Mechlab" : {method} Buy Shredder Armor Upgrade 7: Progressive Gargoyle LEG Speed
"Shredder Mechlab" : {method} Buy Shredder Armor Upgrade 8: Money (Small)
"Shredder Mechlab" : {method} Buy Shredder Armor Upgrade 9: Progressive Shadow ARM Power
"Shredder Mechlab" : {method} Buy Shredder Stun Resist Upgrade 1: Progressive Shredder Stun Resist
"Shredder Mechlab" : {method} Buy Shredder Stun Resist Upgrade 2: Progressive Flail ARM Speed
"Shredder Mechlab" : {method} Buy Shredder Stun Resist Upgrade 3: Progressive Shredder LEG Speed
"Shredder Mechlab" : {method} Buy Shredder Stun Resist Upgrade 4: Progressive Chronos LEG Power
"Shredder Mechlab" : {method} Buy Shredder Stun Resist Upgrade 5: Progressive Nova LEG Power
"Shredder Mechlab" : {method} Buy Shredder Stun Resist Upgrade 6: Progressive Katana ARM Speed
"Shredder Mechlab" : {method} Buy Shredder Stun Resist Upgrade 7: Progressive Thorn LEG Power
"Shredder Mechlab" : {method} Buy Shredder Stun Resist Upgrade 8: Progressive Flail ARM Speed
"Shredder Mechlab" : {method} Buy Shredder Stun Resist Upgrade 9: Progressive Pyros LEG Power
class "Flail Mechlab" #00FF00
"Flail Mechlab" : {method} Buy Flail ARM Power Upgrade 1: Progressive Shredder Stun Resist
"Flail Mechlab" : {method} Buy Flail ARM Power Upgrade 2: Progressive Agility
"Flail Mechlab" : {method} Buy Flail ARM Power Upgrade 3: Progressive Electra Stun Resist
"Flail Mechlab" : {method} Buy Flail ARM Power Upgrade 4: Progressive Gargoyle Stun Resist
"Flail Mechlab" : {method} Buy Flail ARM Power Upgrade 5: Progressive Chronos Armor
"Flail Mechlab" : {method} Buy Flail ARM Power Upgrade 6: Progressive Electra LEG Speed
"Flail Mechlab" : {method} Buy Flail ARM Power Upgrade 7: Progressive Shredder LEG Power
"Flail Mechlab" : {method} Buy Flail ARM Power Upgrade 8: Progressive Thorn ARM Speed
"Flail Mechlab" : {method} Buy Flail ARM Power Upgrade 9: Progressive Flail LEG Power
"Flail Mechlab" : {method} Buy Flail LEG Power Upgrade 1: Progressive Thorn Armor
"Flail Mechlab" : {method} Buy Flail LEG Power Upgrade 2: Progressive Chronos LEG Speed
"Flail Mechlab" : {method} Buy Flail LEG Power Upgrade 3: Progressive Electra ARM Power
"Flail Mechlab" : {method} Buy Flail LEG Power Upgrade 4: Progressive Power
"Flail Mechlab" : {method} Buy Flail LEG Power Upgrade 5: Nothing
"Flail Mechlab" : {method} Buy Flail LEG Power Upgrade 6: Progressive Jaguar Enhancement
"Flail Mechlab" : {method} Buy Flail LEG Power Upgrade 7: Progressive Jaguar LEG Power
"Flail Mechlab" : {method} Buy Flail LEG Power Upgrade 8: Progressive Shadow ARM Speed
"Flail Mechlab" : {method} Buy Flail LEG Power Upgrade 9: Progressive Jaguar Stun Resist
"Flail Mechlab" : {method} Buy Flail ARM Speed Upgrade 1: Progressive Thorn ARM Speed
"Flail Mechlab" : {method} Buy Flail ARM Speed Upgrade 2: Progressive Pyros Armor
"Flail Mechlab" : {method} Buy Flail ARM Speed Upgrade 3: Progressive Nova Stun Resist
"Flail Mechlab" : {method} Buy Flail ARM Speed Upgrade 4: Progressive Katana Armor
"Flail Mechlab" : {method} Buy Flail ARM Speed Upgrade 5: Progressive Katana Stun Resist
"Flail Mechlab" : {method} Buy Flail ARM Speed Upgrade 6: Progressive Jaguar ARM Speed
"Flail Mechlab" : {method} Buy Flail ARM Speed Upgrade 7: Progressive Chronos LEG Power
"Flail Mechlab" : {method} Buy Flail ARM Speed Upgrade 8: Progressive Pyros LEG Speed
"Flail Mechlab" : {method} Buy Flail ARM Speed Upgrade 9: Progressive Chronos Armor
"Flail Mechlab" : {method} Buy Flail LEG Speed Upgrade 1: Progressive Jaguar LEG Power
"Flail Mechlab" : {method} Buy Flail LEG Speed Upgrade 2: Progressive Nova LEG Speed
"Flail Mechlab" : {method} Buy Flail LEG Speed Upgrade 3: Progressive Chronos ARM Power
"Flail Mechlab" : {method} Buy Flail LEG Speed Upgrade 4: Progressive Gargoyle ARM Power
"Flail Mechlab" : {method} Buy Flail LEG Speed Upgrade 5: Progressive Katana Stun Resist
"Flail Mechlab" : {method} Buy Flail LEG Speed Upgrade 6: Progressive Shadow ARM Power
"Flail Mechlab" : {method} Buy Flail LEG Speed Upgrade 7: Progressive Flail ARM Power
"Flail Mechlab" : {method} Buy Flail LEG Speed Upgrade 8: Progressive Flail LEG Speed
"Flail Mechlab" : {method} Buy Flail LEG Speed Upgrade 9: Progressive Electra LEG Power
"Flail Mechlab" : {method} Buy Flail Armor Upgrade 1: Progressive Shadow Armor
"Flail Mechlab" : {method} Buy Flail Armor Upgrade 2: Progressive Pyros ARM Power
"Flail Mechlab" : {method} Buy Flail Armor Upgrade 3: Progressive Endurance
"Flail Mechlab" : {method} Buy Flail Armor Upgrade 4: Progressive Pyros Armor
"Flail Mechlab" : {method} Buy Flail Armor Upgrade 5: Progressive Endurance
"Flail Mechlab" : {method} Buy Flail Armor Upgrade 6: Progressive Flail LEG Speed
"Flail Mechlab" : {method} Buy Flail Armor Upgrade 7: **Gargoyle Unlock**
"Flail Mechlab" : {method} Buy Flail Armor Upgrade 8: Progressive Flail LEG Speed
"Flail Mechlab" : {method} Buy Flail Armor Upgrade 9: Progressive Pyros ARM Speed
"Flail Mechlab" : {method} Buy Flail Stun Resist Upgrade 1: Progressive Agility
"Flail Mechlab" : {method} Buy Flail Stun Resist Upgrade 2: Progressive Pyros Armor
"Flail Mechlab" : {method} Buy Flail Stun Resist Upgrade 3: Progressive Pyros LEG Speed
"Flail Mechlab" : {method} Buy Flail Stun Resist Upgrade 4: Progressive Nova Armor
"Flail Mechlab" : {method} Buy Flail Stun Resist Upgrade 5: Progressive Katana ARM Speed
"Flail Mechlab" : {method} Buy Flail Stun Resist Upgrade 6: Progressive Endurance
"Flail Mechlab" : {method} Buy Flail Stun Resist Upgrade 7: Progressive Thorn ARM Speed
"Flail Mechlab" : {method} Buy Flail Stun Resist Upgrade 8: Progressive Shredder ARM Speed
"Flail Mechlab" : {method} Buy Flail Stun Resist Upgrade 9: Progressive Jaguar Stun Resist
class "Gargoyle Mechlab" #00FF00
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Power Upgrade 1: Progressive Thorn LEG Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Power Upgrade 2: Progressive Flail ARM Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Power Upgrade 3: Money (Large)
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Power Upgrade 4: Progressive Jaguar LEG Power
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Power Upgrade 5: Progressive Shredder Armor
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Power Upgrade 6: Progressive Electra ARM Power
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Power Upgrade 7: Progressive Flail LEG Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Power Upgrade 8: Progressive Gargoyle ARM Power
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Power Upgrade 9: Progressive Flail ARM Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Power Upgrade 1: Progressive Thorn ARM Power
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Power Upgrade 2: Progressive Pyros LEG Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Power Upgrade 3: Progressive Pyros ARM Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Power Upgrade 4: Progressive Flail LEG Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Power Upgrade 5: Progressive Katana ARM Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Power Upgrade 6: Progressive Katana LEG Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Power Upgrade 7: Progressive Agility
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Power Upgrade 8: Progressive Gargoyle Stun Resist
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Power Upgrade 9: Progressive Thorn LEG Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Speed Upgrade 1: Progressive Shadow Armor
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Speed Upgrade 2: Progressive Pyros ARM Power
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Speed Upgrade 3: Progressive Flail ARM Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Speed Upgrade 4: Progressive Shredder Armor
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Speed Upgrade 5: Progressive Gargoyle Stun Resist
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Speed Upgrade 6: Progressive Flail Armor
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Speed Upgrade 7: Progressive Flail Stun Resist
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Speed Upgrade 8: Progressive Katana ARM Power
"Gargoyle Mechlab" : {method} Buy Gargoyle ARM Speed Upgrade 9: Progressive Shredder Enhancement
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Speed Upgrade 1: Progressive Shadow Stun Resist
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Speed Upgrade 2: Progressive Flail Armor
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Speed Upgrade 3: Progressive Gargoyle Armor
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Speed Upgrade 4: Progressive Gargoyle ARM Power
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Speed Upgrade 5: Progressive Jaguar LEG Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Speed Upgrade 6: Progressive Flail ARM Power
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Speed Upgrade 7: Progressive Shredder Armor
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Speed Upgrade 8: Progressive Gargoyle ARM Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle LEG Speed Upgrade 9: Progressive Power
"Gargoyle Mechlab" : {method} Buy Gargoyle Armor Upgrade 1: Progressive Shadow LEG Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle Armor Upgrade 2: Progressive Flail Armor
"Gargoyle Mechlab" : {method} Buy Gargoyle Armor Upgrade 3: Money (Small)
"Gargoyle Mechlab" : {method} Buy Gargoyle Armor Upgrade 4: Progressive Electra Stun Resist
"Gargoyle Mechlab" : {method} Buy Gargoyle Armor Upgrade 5: Progressive Shredder Stun Resist
"Gargoyle Mechlab" : {method} Buy Gargoyle Armor Upgrade 6: Progressive Chronos ARM Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle Armor Upgrade 7: Progressive Flail Stun Resist
"Gargoyle Mechlab" : {method} Buy Gargoyle Armor Upgrade 8: Progressive Shadow Stun Resist
"Gargoyle Mechlab" : {method} Buy Gargoyle Armor Upgrade 9: Progressive Shredder LEG Power
"Gargoyle Mechlab" : {method} Buy Gargoyle Stun Resist Upgrade 1: Nothing
"Gargoyle Mechlab" : {method} Buy Gargoyle Stun Resist Upgrade 2: Progressive Katana LEG Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle Stun Resist Upgrade 3: Progressive Chronos Armor
"Gargoyle Mechlab" : {method} Buy Gargoyle Stun Resist Upgrade 4: Progressive Katana ARM Speed
"Gargoyle Mechlab" : {method} Buy Gargoyle Stun Resist Upgrade 5: Progressive Jaguar ARM Power
"Gargoyle Mechlab" : {method} Buy Gargoyle Stun Resist Upgrade 6: Progressive Katana Armor
"Gargoyle Mechlab" : {method} Buy Gargoyle Stun Resist Upgrade 7: Progressive Katana Armor
"Gargoyle Mechlab" : {method} Buy Gargoyle Stun Resist Upgrade 8: **Chronos Unlock**
"Gargoyle Mechlab" : {method} Buy Gargoyle Stun Resist Upgrade 9: Progressive Katana LEG Power
class "Chronos Mechlab" #00FF00
"Chronos Mechlab" : {method} Buy Chronos ARM Power Upgrade 1: Progressive Electra ARM Speed
"Chronos Mechlab" : {method} Buy Chronos ARM Power Upgrade 2: Progressive Thorn Stun Resist
"Chronos Mechlab" : {method} Buy Chronos ARM Power Upgrade 3: Progressive Pyros Armor
"Chronos Mechlab" : {method} Buy Chronos ARM Power Upgrade 4: Progressive Shadow LEG Power
"Chronos Mechlab" : {method} Buy Chronos ARM Power Upgrade 5: Progressive Shredder ARM Speed
"Chronos Mechlab" : {method} Buy Chronos ARM Power Upgrade 6: Progressive Flail Stun Resist
"Chronos Mechlab" : {method} Buy Chronos ARM Power Upgrade 7: Progressive Katana LEG Speed
"Chronos Mechlab" : {method} Buy Chronos ARM Power Upgrade 8: Progressive Shredder ARM Speed
"Chronos Mechlab" : {method} Buy Chronos ARM Power Upgrade 9: Progressive Gargoyle ARM Speed
"Chronos Mechlab" : {method} Buy Chronos LEG Power Upgrade 1: Progressive Chronos Armor
"Chronos Mechlab" : {method} Buy Chronos LEG Power Upgrade 2: Progressive Chronos ARM Power
"Chronos Mechlab" : {method} Buy Chronos LEG Power Upgrade 3: Progressive Katana LEG Speed
"Chronos Mechlab" : {method} Buy Chronos LEG Power Upgrade 4: Progressive Shadow LEG Power
"Chronos Mechlab" : {method} Buy Chronos LEG Power Upgrade 5: Progressive Pyros ARM Power
"Chronos Mechlab" : {method} Buy Chronos LEG Power Upgrade 6: Progressive Power
"Chronos Mechlab" : {method} Buy Chronos LEG Power Upgrade 7: Progressive Chronos ARM Speed
"Chronos Mechlab" : {method} Buy Chronos LEG Power Upgrade 8: Progressive Nova Armor
"Chronos Mechlab" : {method} Buy Chronos LEG Power Upgrade 9: Progressive Thorn ARM Speed
"Chronos Mechlab" : {method} Buy Chronos ARM Speed Upgrade 1: Progressive Gargoyle LEG Speed
"Chronos Mechlab" : {method} Buy Chronos ARM Speed Upgrade 2: Progressive Power
"Chronos Mechlab" : {method} Buy Chronos ARM Speed Upgrade 3: Progressive Power
"Chronos Mechlab" : {method} Buy Chronos ARM Speed Upgrade 4: Progressive Nova LEG Power
"Chronos Mechlab" : {method} Buy Chronos ARM Speed Upgrade 5: Progressive Thorn Armor
"Chronos Mechlab" : {method} Buy Chronos ARM Speed Upgrade 6: Progressive Chronos ARM Power
"Chronos Mechlab" : {method} Buy Chronos ARM Speed Upgrade 7: Progressive Electra LEG Power
"Chronos Mechlab" : {method} Buy Chronos ARM Speed Upgrade 8: Progressive Chronos Stun Resist
"Chronos Mechlab" : {method} Buy Chronos ARM Speed Upgrade 9: Progressive Jaguar Armor
"Chronos Mechlab" : {method} Buy Chronos LEG Speed Upgrade 1: Nothing
"Chronos Mechlab" : {method} Buy Chronos LEG Speed Upgrade 2: Progressive Shadow Stun Resist
"Chronos Mechlab" : {method} Buy Chronos LEG Speed Upgrade 3: Progressive Power
"Chronos Mechlab" : {method} Buy Chronos LEG Speed Upgrade 4: Progressive Nova LEG Power
"Chronos Mechlab" : {method} Buy Chronos LEG Speed Upgrade 5: Progressive Shredder LEG Speed
"Chronos Mechlab" : {method} Buy Chronos LEG Speed Upgrade 6: Progressive Flail LEG Power
"Chronos Mechlab" : {method} Buy Chronos LEG Speed Upgrade 7: Progressive Jaguar LEG Speed
"Chronos Mechlab" : {method} Buy Chronos LEG Speed Upgrade 8: Progressive Shredder Armor
"Chronos Mechlab" : {method} Buy Chronos LEG Speed Upgrade 9: Progressive Power
"Chronos Mechlab" : {method} Buy Chronos Armor Upgrade 1: Progressive Gargoyle LEG Power
"Chronos Mechlab" : {method} Buy Chronos Armor Upgrade 2: Money (Small)
"Chronos Mechlab" : {method} Buy Chronos Armor Upgrade 3: Progressive Flail Armor
"Chronos Mechlab" : {method} Buy Chronos Armor Upgrade 4: Progressive Gargoyle LEG Speed
"Chronos Mechlab" : {method} Buy Chronos Armor Upgrade 5: Progressive Chronos ARM Speed
"Chronos Mechlab" : {method} Buy Chronos Armor Upgrade 6: Progressive Shredder ARM Speed
"Chronos Mechlab" : {method} Buy Chronos Armor Upgrade 7: Progressive Jaguar Armor
"Chronos Mechlab" : {method} Buy Chronos Armor Upgrade 8: Progressive Shadow ARM Power
"Chronos Mechlab" : {method} Buy Chronos Armor Upgrade 9: Nothing
"Chronos Mechlab" : {method} Buy Chronos Stun Resist Upgrade 1: Progressive Electra Stun Resist
"Chronos Mechlab" : {method} Buy Chronos Stun Resist Upgrade 2: Progressive Agility
"Chronos Mechlab" : {method} Buy Chronos Stun Resist Upgrade 3: Progressive Thorn ARM Speed
"Chronos Mechlab" : {method} Buy Chronos Stun Resist Upgrade 4: Progressive Flail LEG Power
"Chronos Mechlab" : {method} Buy Chronos Stun Resist Upgrade 5: Progressive Katana LEG Speed
"Chronos Mechlab" : {method} Buy Chronos Stun Resist Upgrade 6: Progressive Nova Stun Resist
"Chronos Mechlab" : {method} Buy Chronos Stun Resist Upgrade 7: Progressive Pyros ARM Speed
"Chronos Mechlab" : {method} Buy Chronos Stun Resist Upgrade 8: Progressive Thorn Stun Resist
"Chronos Mechlab" : {method} Buy Chronos Stun Resist Upgrade 9: Progressive Thorn LEG Speed
class "Nova Mechlab" #00FF00
"Nova Mechlab" : {method} Buy Nova ARM Power Upgrade 1: Progressive Chronos Enhancement
"Nova Mechlab" : {method} Buy Nova ARM Power Upgrade 2: Progressive Katana LEG Speed
"Nova Mechlab" : {method} Buy Nova ARM Power Upgrade 3: Progressive Shadow Stun Resist
"Nova Mechlab" : {method} Buy Nova ARM Power Upgrade 4: Progressive Shredder ARM Power
"Nova Mechlab" : {method} Buy Nova ARM Power Upgrade 5: Progressive Pyros Armor
"Nova Mechlab" : {method} Buy Nova ARM Power Upgrade 6: Progressive Gargoyle ARM Speed
"Nova Mechlab" : {method} Buy Nova ARM Power Upgrade 7: Progressive Agility
"Nova Mechlab" : {method} Buy Nova ARM Power Upgrade 8: Progressive Nova LEG Speed
"Nova Mechlab" : {method} Buy Nova ARM Power Upgrade 9: Progressive Endurance
"Nova Mechlab" : {method} Buy Nova LEG Power Upgrade 1: Progressive Endurance
"Nova Mechlab" : {method} Buy Nova LEG Power Upgrade 2: Progressive Nova Armor
"Nova Mechlab" : {method} Buy Nova LEG Power Upgrade 3: Progressive Power
"Nova Mechlab" : {method} Buy Nova LEG Power Upgrade 4: Progressive Thorn Armor
"Nova Mechlab" : {method} Buy Nova LEG Power Upgrade 5: **Shredder Unlock**
"Nova Mechlab" : {method} Buy Nova LEG Power Upgrade 6: Progressive Flail Enhancement
"Nova Mechlab" : {method} Buy Nova LEG Power Upgrade 7: Progressive Shredder Stun Resist
"Nova Mechlab" : {method} Buy Nova LEG Power Upgrade 8: Progressive Chronos LEG Speed
"Nova Mechlab" : {method} Buy Nova LEG Power Upgrade 9: Progressive Shadow Armor
"Nova Mechlab" : {method} Buy Nova ARM Speed Upgrade 1: Progressive Shadow Enhancement
"Nova Mechlab" : {method} Buy Nova ARM Speed Upgrade 2: Progressive Jaguar Stun Resist
"Nova Mechlab" : {method} Buy Nova ARM Speed Upgrade 3: Progressive Electra Armor
"Nova Mechlab" : {method} Buy Nova ARM Speed Upgrade 4: Progressive Nova ARM Speed
"Nova Mechlab" : {method} Buy Nova ARM Speed Upgrade 5: Progressive Electra LEG Speed
"Nova Mechlab" : {method} Buy Nova ARM Speed Upgrade 6: Progressive Chronos LEG Speed
"Nova Mechlab" : {method} Buy Nova ARM Speed Upgrade 7: Progressive Chronos LEG Power
"Nova Mechlab" : {method} Buy Nova ARM Speed Upgrade 8: Progressive Pyros ARM Speed
"Nova Mechlab" : {method} Buy Nova ARM Speed Upgrade 9: Progressive Shredder ARM Speed
"Nova Mechlab" : {method} Buy Nova LEG Speed Upgrade 1: Progressive Gargoyle ARM Power
"Nova Mechlab" : {method} Buy Nova LEG Speed Upgrade 2: Progressive Chronos Stun Resist
"Nova Mechlab" : {method} Buy Nova LEG Speed Upgrade 3: Nothing
"Nova Mechlab" : {method} Buy Nova LEG Speed Upgrade 4: Progressive Gargoyle Armor
"Nova Mechlab" : {method} Buy Nova LEG Speed Upgrade 5: Progressive Power
"Nova Mechlab" : {method} Buy Nova LEG Speed Upgrade 6: Progressive Electra LEG Speed
"Nova Mechlab" : {method} Buy Nova LEG Speed Upgrade 7: Progressive Gargoyle ARM Power
"Nova Mechlab" : {method} Buy Nova LEG Speed Upgrade 8: Progressive Flail ARM Power
"Nova Mechlab" : {method} Buy Nova LEG Speed Upgrade 9: Progressive Katana Stun Resist
"Nova Mechlab" : {method} Buy Nova Armor Upgrade 1: Progressive Thorn ARM Power
"Nova Mechlab" : {method} Buy Nova Armor Upgrade 2: Progressive Agility
"Nova Mechlab" : {method} Buy Nova Armor Upgrade 3: Progressive Jaguar Stun Resist
"Nova Mechlab" : {method} Buy Nova Armor Upgrade 4: Progressive Jaguar ARM Power
"Nova Mechlab" : {method} Buy Nova Armor Upgrade 5: Progressive Electra Stun Resist
"Nova Mechlab" : {method} Buy Nova Armor Upgrade 6: Progressive Nova Armor
"Nova Mechlab" : {method} Buy Nova Armor Upgrade 7: Progressive Pyros Stun Resist
"Nova Mechlab" : {method} Buy Nova Armor Upgrade 8: Progressive Endurance
"Nova Mechlab" : {method} Buy Nova Armor Upgrade 9: Progressive Shadow Armor
"Nova Mechlab" : {method} Buy Nova Stun Resist Upgrade 1: Progressive Thorn ARM Speed
"Nova Mechlab" : {method} Buy Nova Stun Resist Upgrade 2: Progressive Jaguar Armor
"Nova Mechlab" : {method} Buy Nova Stun Resist Upgrade 3: Progressive Chronos Armor
"Nova Mechlab" : {method} Buy Nova Stun Resist Upgrade 4: Progressive Power
"Nova Mechlab" : {method} Buy Nova Stun Resist Upgrade 5: Progressive Thorn Armor
"Nova Mechlab" : {method} Buy Nova Stun Resist Upgrade 6: Progressive Nova ARM Speed
"Nova Mechlab" : {method} Buy Nova Stun Resist Upgrade 7: Progressive Jaguar LEG Power
"Nova Mechlab" : {method} Buy Nova Stun Resist Upgrade 8: Progressive Shadow LEG Power
"Nova Mechlab" : {method} Buy Nova Stun Resist Upgrade 9: Progressive Electra LEG Speed
class "Pilot Training" #00FF00
"Pilot Training" : {method} Train Power Level 1: Progressive Shredder LEG Speed
"Pilot Training" : {method} Train Power Level 2: Progressive Jaguar ARM Speed
"Pilot Training" : {method} Train Power Level 3: Progressive Electra ARM Power
"Pilot Training" : {method} Train Power Level 4: Progressive Flail Armor
"Pilot Training" : {method} Train Power Level 5: Progressive Agility
"Pilot Training" : {method} Train Power Level 6: Progressive Electra ARM Power
"Pilot Training" : {method} Train Power Level 7: Progressive Shadow LEG Speed
"Pilot Training" : {method} Train Power Level 8: Progressive Pyros LEG Speed
"Pilot Training" : {method} Train Power Level 9: Progressive Nova LEG Power
"Pilot Training" : {method} Train Power Level 10: Progressive Shredder ARM Power
"Pilot Training" : {method} Train Power Level 11: Progressive Chronos LEG Power
"Pilot Training" : {method} Train Power Level 12: Progressive Gargoyle LEG Speed
"Pilot Training" : {method} Train Power Level 13: Progressive Shadow ARM Power
"Pilot Training" : {method} Train Power Level 14: Progressive Agility
"Pilot Training" : {method} Train Power Level 15: Progressive Nova Armor
"Pilot Training" : {method} Train Power Level 16: Progressive Shredder ARM Speed
"Pilot Training" : {method} Train Power Level 17: Progressive Pyros ARM Speed
"Pilot Training" : {method} Train Power Level 18: Progressive Flail Armor
"Pilot Training" : {method} Train Power Level 19: Progressive Endurance
"Pilot Training" : {method} Train Power Level 20: Progressive Katana LEG Power
"Pilot Training" : {method} Train Power Level 21: Progressive Power
"Pilot Training" : {method} Train Power Level 22: Progressive Flail ARM Power
"Pilot Training" : {method} Train Power Level 23: Progressive Electra Armor
"Pilot Training" : {method} Train Power Level 24: Progressive Chronos ARM Power
"Pilot Training" : {method} Train Power Level 25: Progressive Nova LEG Speed
"Pilot Training" : {method} Train Agility Level 1: Progressive Nova LEG Speed
"Pilot Training" : {method} Train Agility Level 2: Progressive Shadow Stun Resist
"Pilot Training" : {method} Train Agility Level 3: Progressive Shadow Armor
"Pilot Training" : {method} Train Agility Level 4: Progressive Gargoyle Stun Resist
"Pilot Training" : {method} Train Agility Level 5: Progressive Electra LEG Power
"Pilot Training" : {method} Train Agility Level 6: Progressive Electra Armor
"Pilot Training" : {method} Train Agility Level 7: Progressive Katana ARM Speed
"Pilot Training" : {method} Train Agility Level 8: Progressive Pyros ARM Power
"Pilot Training" : {method} Train Agility Level 9: Nothing
"Pilot Training" : {method} Train Agility Level 10: Progressive Shadow LEG Speed
"Pilot Training" : {method} Train Agility Level 11: Progressive Flail LEG Speed
"Pilot Training" : {method} Train Agility Level 12: Progressive Nova ARM Power
"Pilot Training" : {method} Train Agility Level 13: Progressive Jaguar LEG Power
"Pilot Training" : {method} Train Agility Level 14: Progressive Katana LEG Power
"Pilot Training" : {method} Train Agility Level 15: **Flail Unlock**
"Pilot Training" : {method} Train Agility Level 16: Progressive Thorn Armor
"Pilot Training" : {method} Train Agility Level 17: Progressive Nova ARM Power
"Pilot Training" : {method} Train Agility Level 18: Progressive Shadow Stun Resist
"Pilot Training" : {method} Train Agility Level 19: Progressive Pyros LEG Power
"Pilot Training" : {method} Train Agility Level 20: Progressive Power
"Pilot Training" : {method} Train Agility Level 21: Progressive Flail ARM Power
"Pilot Training" : {method} Train Agility Level 22: Progressive Shredder ARM Speed
"Pilot Training" : {method} Train Agility Level 23: Progressive Flail ARM Power
"Pilot Training" : {method} Train Agility Level 24: Progressive Endurance
"Pilot Training" : {method} Train Agility Level 25: Nothing
"Pilot Training" : {method} Train Endurance Level 1: Money (Small)
"Pilot Training" : {method} Train Endurance Level 2: Progressive Nova ARM Power
"Pilot Training" : {method} Train Endurance Level 3: **Pyros Unlock**
"Pilot Training" : {method} Train Endurance Level 4: Progressive Chronos Stun Resist
"Pilot Training" : {method} Train Endurance Level 5: Money (Large)
"Pilot Training" : {method} Train Endurance Level 6: Nothing
"Pilot Training" : {method} Train Endurance Level 7: Progressive Flail LEG Power
"Pilot Training" : {method} Train Endurance Level 8: Progressive Electra Stun Resist
"Pilot Training" : {method} Train Endurance Level 9: Progressive Pyros ARM Power
"Pilot Training" : {method} Train Endurance Level 10: Progressive Flail ARM Power
"Pilot Training" : {method} Train Endurance Level 11: Progressive Jaguar LEG Power
"Pilot Training" : {method} Train Endurance Level 12: Progressive Gargoyle Enhancement
"Pilot Training" : {method} Train Endurance Level 13: Progressive Shredder LEG Power
"Pilot Training" : {method} Train Endurance Level 14: Progressive Thorn Armor
"Pilot Training" : {method} Train Endurance Level 15: Progressive Shadow Armor
"Pilot Training" : {method} Train Endurance Level 16: Progressive Shadow LEG Speed
"Pilot Training" : {method} Train Endurance Level 17: Progressive Gargoyle LEG Power
"Pilot Training" : {method} Train Endurance Level 18: Progressive Thorn LEG Speed
"Pilot Training" : {method} Train Endurance Level 19: Progressive Gargoyle Stun Resist
"Pilot Training" : {method} Train Endurance Level 20: Progressive Gargoyle LEG Power
"Pilot Training" : {method} Train Endurance Level 21: Progressive Jaguar Stun Resist
"Pilot Training" : {method} Train Endurance Level 22: Progressive Agility
"Pilot Training" : {method} Train Endurance Level 23: Progressive Electra ARM Speed
"Pilot Training" : {method} Train Endurance Level 24: Money (Small)
"Pilot Training" : {method} Train Endurance Level 25: Progressive Agility
@enduml